# Generated by Django 5.2.3 on 2025-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('preview_image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='preview image')),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
                'ordering': ['name'],
            },
        ),
    ]
