services:
  web:
    image: ghcr.io/marcaltmann/explorer
    command: gunicorn explorer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    env_file:
      - ./.postgres-container.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5432:5432
  nginx:
    image: ghcr.io/marcaltmann/nginx
    volumes:
      - static_volume:/home/app/web/static
      - certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  certs:
  db_data:
  static_volume:
