name: explorer

include:
  - infra.yaml

services:
  web:
    image: ghcr.io/marcaltmann/explorer
    command: gunicorn explorer.wsgi:application --bind 0.0.0.0:8000
    configs:
      - source: app_config
        target: /app/my_config
    ports:
      - 8000:8000
    env_file:
      - ./envs/web.env
    depends_on:
      - db

configs:
  app_config:
    content: |
      debug=${DEBUG}
      spring.application.admin_enabled=${DEBUG}
