name: explorer

include:
  - infra.yaml

services:
  web:
    image: ghcr.io/marcaltmann/explorer
    command: gunicorn explorer.wsgi:application --bind 0.0.0.0:8000
    restart: always
    mem_limit: 512mb
    configs:
      - source: app_config
        target: /app/my_config
    env_file:
      - ./envs/web.env
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db
configs:
  app_config:
    content: |
      debug=true
      spring.application.admin_enabled=true

networks:
  front-tier: {}
  back-tier: {}
