services:
  web:
    build: ./app
    command: gunicorn explorer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  certs:
  mariadb_data:
  static_volume:
