services:
  proxy:
    image: nginx:1.27
    container_name: explorer-proxy
    restart: always
    mem_limit: 128mb
    volumes:
      - type: bind
        source: ./proxy/nginx-staging.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    networks:
      - front-tier
    depends_on:
      - web
  db:
    image: postgres:15
    container_name: explorer-db
    restart: always
    mem_limit: 512mb
    shm_size: 128mb
    env_file:
      - ./envs/db.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - back-tier

volumes:
  db_data:
    labels:
      net.media-explorer.description: "Database volume"
