# Generated by Django 5.1b1 on 2024-07-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0003_remove_resource_duration_remove_resource_media_type_and_more",
        ),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcript",
            name="resource",
        ),
        migrations.AddField(
            model_name="transcript",
            name="media_file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="archive.mediafile",
                verbose_name="media file",
            ),
            preserve_default=False,
        ),
    ]
