service: explorer
image: marcaltmann/explorer

env:
  secret:
    - SECRET_KEY
    - DATABASE_URL
    - CACHE_URL

proxy:
  ssl: true
  host: media-explorer.net
  app_port: 8000
  healthcheck:
    path: /
    interval: 60

servers:
  web:
    hosts:
      - 1.2.3.4
    cmd: bin/app web

  #worker:
  #  hosts:
  #    - 1.2.3.4
  #  cmd: bin/app worker

  #scheduler:
  #  hosts:
  #    - 1.2.3.4
  #  cmd: bin/app scheduler

accessories:
  db:
    image: postgres:15
    host: 1.2.3.4
    port: 127.0.0.1:5432:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

  #redis:
  #  image: redis:7.0
  #  host: 1.2.3.4
  #  port: 127.0.0.1:6379:6379
  #  cmd: --maxmemory 200m --maxmemory-policy allkeys-lru
  #  volumes:
  #    - /var/redis/data:/data

registry:
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

builder:
  arch: amd64
  remote: ssh://1.2.3.4
  cache:
    type: registry
    options: mode=max
    image: your-repo/example-build-cache

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /opt/app/staticfiles
