# Generated by Django 5.1b1 on 2024-07-29 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_remove_resource_pub_date_resource_production_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="media_type",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="media_url",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="production_date",
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "media_type",
                    models.CharField(
                        default="video/mp4",
                        help_text="Enter MIME type e.g. 'video/mp4'.",
                        max_length=100,
                        verbose_name="media type",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        default="", max_length=300, verbose_name="media url"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="",
                        verbose_name="poster image",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="duration"
                    ),
                ),
                (
                    "production_date",
                    models.DateTimeField(null=True, verbose_name="production date"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "media file",
                "verbose_name_plural": "media files",
                "ordering": ["order"],
                "indexes": [
                    models.Index(fields=["order"], name="archive_med_order_fb6910_idx")
                ],
            },
        ),
    ]
