# Generated by Django 5.1b1 on 2024-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_remove_mediafile_media_type_mediafile_subtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("audio", "Audio")],
                default="video",
                help_text="Select the first part of MIME type.",
                max_length=20,
                verbose_name="media type",
            ),
        ),
    ]
