---
- name: Set up MariaDB for development
  hosts: localhost
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: safe

    - name: Install required system packages
      apt:
        pkg:
          - build-essential
          - default-libmysqlclient-dev
          - libmariadb-dev
          - mariadb-server
          - pkg-config
          - python3-dev
          - python3-pymysql
          - python3-pip

        state: latest
        update_cache: true

    - name: Create a new database with name "explorer"
      community.mysql.mysql_db:
        name: explorer
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Check that root user has password "password"
      community.mysql.mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: password
        name: root
        password: password
        state: present
        column_case_sensitive: true
