# Generated by Django 5.1b1 on 2024-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_delete_location_delete_miscellaneousentity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra information specific to entity types",
                verbose_name="extra",
            ),
        ),
    ]
