name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://elefant:password@postgres/explorer
      DJANGO_ENV: test
      SECRET_KEY: test-secret-key
      EMAIL_URL: dummymail://

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: elefant
          POSTGRES_DB: explorer
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up MySQL
        working-directory: ./app
        run: |
          sudo service mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          cp my.cnf.example my.cnf
      - name: Build assets with Node.js
        working-directory: ./app
        run: |
          npm install
          npm run build
      - name: Run Tests
        working-directory: ./app
        run: |
          uv run manage.py test
