name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: explorer
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Set up MySQL
        working-directory: ./app
        run: |
          sudo service mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          cp my.cnf.example my.cnf
      - name: Install Python Dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build assets with Node.js
        working-directory: ./app
        run: |
          npm install
          npm run build
      - name: Run Tests
        working-directory: ./app
        run: |
          python manage.py test
