name: Test Django application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://elefant:password@localhost/explorer
      DJANGO_ENV: test
      DEBUG: on
      SECRET_KEY: test-secret-key
      EMAIL_URL: dummymail://

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: elefant
          POSTGRES_DB: explorer
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
      - name: Build assets with Node.js
        run: |
          npm install
          npm run build
      - name: Run Tests
        run: |
          uv run manage.py collectstatic
          uv run manage.py test
