name: Docker image

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract version from pyproject.toml
        id: get_version
        working-directory: .
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT      
      -
        name: Build and push the application image
        working-directory: .
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          echo "Building image for version $VERSION"

          docker buildx build \
            --build-arg VERSION="$VERSION" \
            --tag "ghcr.io/marcaltmann/media-explorer:latest" \
            --tag "ghcr.io/marcaltmann/media-explorer:$VERSION" \
            .
          docker push ghcr.io/marcaltmann/media-explorer:latest
          docker push ghcr.io/marcaltmann/media-explorer:$VERSION
