name: Docker image

on:
  push:
    tags:
      - 0.**
      - 1.**

permissions: write-all

jobs:
  build_web_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the application image
        working-directory: .
        run: |
          docker build --tag ghcr.io/marcaltmann/media-explorer .
          docker tag ghcr.io/marcaltmann/media-explorer ghcr.io/marcaltmann/media-explorer:${{github.ref_name}}
          docker push ghcr.io/marcaltmann/media-explorer
          docker push ghcr.io/marcaltmann/media-explorer:${{github.ref_name}}
