name: Docker Image CI for GHCR

on:
  push:
    tags:
      - 1.**

permissions: write-all

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the image
        working-directory: .
        run : |
          docker build --tag ghcr.io/marcaltmann/explorer .
          docker tag ghcr.io/marcaltmann/explorer ghcr.io/marcaltmann/explorer:${{github.ref_name}}
          docker push ghcr.io/marcaltmann/explorer
          docker push ghcr.io/marcaltmann/explorer:${{github.ref_name}}
